package com.example.bss.pojo;

import java.io.Serializable;

public class BssCostDepartment implements Serializable {
    /**
     * 主键id
     * 表字段 : bss_cost_department.id
     */
    private Integer id;

    /**
     * 费用归属部门名称
     * 表字段 : bss_cost_department.bmmc
     */
    private String bmmc;

    /**
     * 预留字段1
     * 表字段 : bss_cost_department.reserved1
     */
    private String reserved1;

    /**
     * 预留字段2
     * 表字段 : bss_cost_department.reserved2
     */
    private String reserved2;

    /**
     * 预留字段3
     * 表字段 : bss_cost_department.reserved3
     */
    private String reserved3;

    /**
     * 创建时间
     * 表字段 : bss_cost_department.create_time
     */
    private String createTime;

    /**
     * 修改时间
     * 表字段 : bss_cost_department.update_time
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_cost_department
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键id 字段:bss_cost_department.id
     *
     * @return bss_cost_department.id, 主键id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键id 字段:bss_cost_department.id
     *
     * @param id the value for bss_cost_department.id, 主键id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 费用归属部门名称 字段:bss_cost_department.bmmc
     *
     * @return bss_cost_department.bmmc, 费用归属部门名称
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * 设置 费用归属部门名称 字段:bss_cost_department.bmmc
     *
     * @param bmmc the value for bss_cost_department.bmmc, 费用归属部门名称
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * 获取 预留字段1 字段:bss_cost_department.reserved1
     *
     * @return bss_cost_department.reserved1, 预留字段1
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * 设置 预留字段1 字段:bss_cost_department.reserved1
     *
     * @param reserved1 the value for bss_cost_department.reserved1, 预留字段1
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * 获取 预留字段2 字段:bss_cost_department.reserved2
     *
     * @return bss_cost_department.reserved2, 预留字段2
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * 设置 预留字段2 字段:bss_cost_department.reserved2
     *
     * @param reserved2 the value for bss_cost_department.reserved2, 预留字段2
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * 获取 预留字段3 字段:bss_cost_department.reserved3
     *
     * @return bss_cost_department.reserved3, 预留字段3
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * 设置 预留字段3 字段:bss_cost_department.reserved3
     *
     * @param reserved3 the value for bss_cost_department.reserved3, 预留字段3
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * 获取 创建时间 字段:bss_cost_department.create_time
     *
     * @return bss_cost_department.create_time, 创建时间
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:bss_cost_department.create_time
     *
     * @param createTime the value for bss_cost_department.create_time, 创建时间
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * 获取 修改时间 字段:bss_cost_department.update_time
     *
     * @return bss_cost_department.update_time, 修改时间
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 修改时间 字段:bss_cost_department.update_time
     *
     * @param updateTime the value for bss_cost_department.update_time, 修改时间
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}