package com.example.bss.pojo;

import java.util.ArrayList;
import java.util.List;

public class BssProjectPriceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_project_price
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_project_price
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_project_price
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *  鏋勯�犳煡璇㈡潯浠�,bss_project_price
     */
    public BssProjectPriceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  璁剧疆鎺掑簭瀛楁,bss_project_price
     *
     * @param orderByClause 鎺掑簭瀛楁
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  鑾峰彇鎺掑簭瀛楁,bss_project_price
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  璁剧疆杩囨护閲嶅鏁版嵁,bss_project_price
     *
     * @param distinct 鏄惁杩囨护閲嶅鏁版嵁
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  鏄惁杩囨护閲嶅鏁版嵁,bss_project_price
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  鑾峰彇褰撳墠鐨勬煡璇㈡潯浠跺疄渚�,bss_project_price
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,bss_project_price
     *
     * @param criteria 杩囨护鏉′欢瀹炰緥
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,bss_project_price
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  鍒涘缓涓�涓煡璇㈡潯浠�,bss_project_price
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  鍐呴儴鏋勫缓鏌ヨ鏉′欢瀵硅薄,bss_project_price
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  娓呴櫎鏌ヨ鏉′欢,bss_project_price
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 椤圭洰鍗曚环琛�
     * GeneratedCriteria
     * 鏁版嵁搴撹〃锛歜ss_project_price
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andDjIsNull() {
            addCriterion("dj is null");
            return (Criteria) this;
        }

        public Criteria andDjIsNotNull() {
            addCriterion("dj is not null");
            return (Criteria) this;
        }

        public Criteria andDjEqualTo(String value) {
            addCriterion("dj =", value, "dj");
            return (Criteria) this;
        }

        public Criteria andDjNotEqualTo(String value) {
            addCriterion("dj <>", value, "dj");
            return (Criteria) this;
        }

        public Criteria andDjGreaterThan(String value) {
            addCriterion("dj >", value, "dj");
            return (Criteria) this;
        }

        public Criteria andDjGreaterThanOrEqualTo(String value) {
            addCriterion("dj >=", value, "dj");
            return (Criteria) this;
        }

        public Criteria andDjLessThan(String value) {
            addCriterion("dj <", value, "dj");
            return (Criteria) this;
        }

        public Criteria andDjLessThanOrEqualTo(String value) {
            addCriterion("dj <=", value, "dj");
            return (Criteria) this;
        }

        public Criteria andDjLike(String value) {
            addCriterion("dj like", value, "dj");
            return (Criteria) this;
        }

        public Criteria andDjNotLike(String value) {
            addCriterion("dj not like", value, "dj");
            return (Criteria) this;
        }

        public Criteria andDjIn(List<String> values) {
            addCriterion("dj in", values, "dj");
            return (Criteria) this;
        }

        public Criteria andDjNotIn(List<String> values) {
            addCriterion("dj not in", values, "dj");
            return (Criteria) this;
        }

        public Criteria andDjBetween(String value1, String value2) {
            addCriterion("dj between", value1, value2, "dj");
            return (Criteria) this;
        }

        public Criteria andDjNotBetween(String value1, String value2) {
            addCriterion("dj not between", value1, value2, "dj");
            return (Criteria) this;
        }

        public Criteria andSlIsNull() {
            addCriterion("sl is null");
            return (Criteria) this;
        }

        public Criteria andSlIsNotNull() {
            addCriterion("sl is not null");
            return (Criteria) this;
        }

        public Criteria andSlEqualTo(String value) {
            addCriterion("sl =", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotEqualTo(String value) {
            addCriterion("sl <>", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThan(String value) {
            addCriterion("sl >", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThanOrEqualTo(String value) {
            addCriterion("sl >=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThan(String value) {
            addCriterion("sl <", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThanOrEqualTo(String value) {
            addCriterion("sl <=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLike(String value) {
            addCriterion("sl like", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotLike(String value) {
            addCriterion("sl not like", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlIn(List<String> values) {
            addCriterion("sl in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotIn(List<String> values) {
            addCriterion("sl not in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlBetween(String value1, String value2) {
            addCriterion("sl between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotBetween(String value1, String value2) {
            addCriterion("sl not between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andZysjeIsNull() {
            addCriterion("zysje is null");
            return (Criteria) this;
        }

        public Criteria andZysjeIsNotNull() {
            addCriterion("zysje is not null");
            return (Criteria) this;
        }

        public Criteria andZysjeEqualTo(String value) {
            addCriterion("zysje =", value, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeNotEqualTo(String value) {
            addCriterion("zysje <>", value, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeGreaterThan(String value) {
            addCriterion("zysje >", value, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeGreaterThanOrEqualTo(String value) {
            addCriterion("zysje >=", value, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeLessThan(String value) {
            addCriterion("zysje <", value, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeLessThanOrEqualTo(String value) {
            addCriterion("zysje <=", value, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeLike(String value) {
            addCriterion("zysje like", value, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeNotLike(String value) {
            addCriterion("zysje not like", value, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeIn(List<String> values) {
            addCriterion("zysje in", values, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeNotIn(List<String> values) {
            addCriterion("zysje not in", values, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeBetween(String value1, String value2) {
            addCriterion("zysje between", value1, value2, "zysje");
            return (Criteria) this;
        }

        public Criteria andZysjeNotBetween(String value1, String value2) {
            addCriterion("zysje not between", value1, value2, "zysje");
            return (Criteria) this;
        }

        public Criteria andXz19IsNull() {
            addCriterion("xz_19 is null");
            return (Criteria) this;
        }

        public Criteria andXz19IsNotNull() {
            addCriterion("xz_19 is not null");
            return (Criteria) this;
        }

        public Criteria andXz19EqualTo(String value) {
            addCriterion("xz_19 =", value, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19NotEqualTo(String value) {
            addCriterion("xz_19 <>", value, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19GreaterThan(String value) {
            addCriterion("xz_19 >", value, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19GreaterThanOrEqualTo(String value) {
            addCriterion("xz_19 >=", value, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19LessThan(String value) {
            addCriterion("xz_19 <", value, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19LessThanOrEqualTo(String value) {
            addCriterion("xz_19 <=", value, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19Like(String value) {
            addCriterion("xz_19 like", value, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19NotLike(String value) {
            addCriterion("xz_19 not like", value, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19In(List<String> values) {
            addCriterion("xz_19 in", values, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19NotIn(List<String> values) {
            addCriterion("xz_19 not in", values, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19Between(String value1, String value2) {
            addCriterion("xz_19 between", value1, value2, "xz19");
            return (Criteria) this;
        }

        public Criteria andXz19NotBetween(String value1, String value2) {
            addCriterion("xz_19 not between", value1, value2, "xz19");
            return (Criteria) this;
        }

        public Criteria andDy18IsNull() {
            addCriterion("dy_18 is null");
            return (Criteria) this;
        }

        public Criteria andDy18IsNotNull() {
            addCriterion("dy_18 is not null");
            return (Criteria) this;
        }

        public Criteria andDy18EqualTo(String value) {
            addCriterion("dy_18 =", value, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18NotEqualTo(String value) {
            addCriterion("dy_18 <>", value, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18GreaterThan(String value) {
            addCriterion("dy_18 >", value, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18GreaterThanOrEqualTo(String value) {
            addCriterion("dy_18 >=", value, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18LessThan(String value) {
            addCriterion("dy_18 <", value, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18LessThanOrEqualTo(String value) {
            addCriterion("dy_18 <=", value, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18Like(String value) {
            addCriterion("dy_18 like", value, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18NotLike(String value) {
            addCriterion("dy_18 not like", value, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18In(List<String> values) {
            addCriterion("dy_18 in", values, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18NotIn(List<String> values) {
            addCriterion("dy_18 not in", values, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18Between(String value1, String value2) {
            addCriterion("dy_18 between", value1, value2, "dy18");
            return (Criteria) this;
        }

        public Criteria andDy18NotBetween(String value1, String value2) {
            addCriterion("dy_18 not between", value1, value2, "dy18");
            return (Criteria) this;
        }

        public Criteria andYzfIsNull() {
            addCriterion("yzf is null");
            return (Criteria) this;
        }

        public Criteria andYzfIsNotNull() {
            addCriterion("yzf is not null");
            return (Criteria) this;
        }

        public Criteria andYzfEqualTo(String value) {
            addCriterion("yzf =", value, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfNotEqualTo(String value) {
            addCriterion("yzf <>", value, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfGreaterThan(String value) {
            addCriterion("yzf >", value, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfGreaterThanOrEqualTo(String value) {
            addCriterion("yzf >=", value, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfLessThan(String value) {
            addCriterion("yzf <", value, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfLessThanOrEqualTo(String value) {
            addCriterion("yzf <=", value, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfLike(String value) {
            addCriterion("yzf like", value, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfNotLike(String value) {
            addCriterion("yzf not like", value, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfIn(List<String> values) {
            addCriterion("yzf in", values, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfNotIn(List<String> values) {
            addCriterion("yzf not in", values, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfBetween(String value1, String value2) {
            addCriterion("yzf between", value1, value2, "yzf");
            return (Criteria) this;
        }

        public Criteria andYzfNotBetween(String value1, String value2) {
            addCriterion("yzf not between", value1, value2, "yzf");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("bz is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("bz is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("bz =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("bz <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("bz >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("bz >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("bz <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("bz <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("bz like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("bz not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("bz in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("bz not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("bz between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("bz not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNull() {
            addCriterion("reserved1 is null");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNotNull() {
            addCriterion("reserved1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved1EqualTo(String value) {
            addCriterion("reserved1 =", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotEqualTo(String value) {
            addCriterion("reserved1 <>", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThan(String value) {
            addCriterion("reserved1 >", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("reserved1 >=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThan(String value) {
            addCriterion("reserved1 <", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThanOrEqualTo(String value) {
            addCriterion("reserved1 <=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Like(String value) {
            addCriterion("reserved1 like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotLike(String value) {
            addCriterion("reserved1 not like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1In(List<String> values) {
            addCriterion("reserved1 in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotIn(List<String> values) {
            addCriterion("reserved1 not in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Between(String value1, String value2) {
            addCriterion("reserved1 between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotBetween(String value1, String value2) {
            addCriterion("reserved1 not between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * 绫绘敞閲�
     * Criteria
     * 鏁版嵁搴撹〃锛歜ss_project_price
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 椤圭洰鍗曚环琛�
     * Criterion
     * 鏁版嵁搴撹〃锛歜ss_project_price
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}