package com.example.bss.pojo;

import java.util.ArrayList;
import java.util.List;

public class BssProjectInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_project_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_project_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_project_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *  构造查询条件,bss_project_info
     */
    public BssProjectInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,bss_project_info
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,bss_project_info
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,bss_project_info
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,bss_project_info
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,bss_project_info
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,bss_project_info
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,bss_project_info
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,bss_project_info
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,bss_project_info
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,bss_project_info
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 项目明细表
     * GeneratedCriteria
     * 数据库表：bss_project_info
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXmlxIsNull() {
            addCriterion("xmlx is null");
            return (Criteria) this;
        }

        public Criteria andXmlxIsNotNull() {
            addCriterion("xmlx is not null");
            return (Criteria) this;
        }

        public Criteria andXmlxEqualTo(String value) {
            addCriterion("xmlx =", value, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxNotEqualTo(String value) {
            addCriterion("xmlx <>", value, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxGreaterThan(String value) {
            addCriterion("xmlx >", value, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxGreaterThanOrEqualTo(String value) {
            addCriterion("xmlx >=", value, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxLessThan(String value) {
            addCriterion("xmlx <", value, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxLessThanOrEqualTo(String value) {
            addCriterion("xmlx <=", value, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxLike(String value) {
            addCriterion("xmlx like", value, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxNotLike(String value) {
            addCriterion("xmlx not like", value, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxIn(List<String> values) {
            addCriterion("xmlx in", values, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxNotIn(List<String> values) {
            addCriterion("xmlx not in", values, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxBetween(String value1, String value2) {
            addCriterion("xmlx between", value1, value2, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmlxNotBetween(String value1, String value2) {
            addCriterion("xmlx not between", value1, value2, "xmlx");
            return (Criteria) this;
        }

        public Criteria andXmmcIsNull() {
            addCriterion("xmmc is null");
            return (Criteria) this;
        }

        public Criteria andXmmcIsNotNull() {
            addCriterion("xmmc is not null");
            return (Criteria) this;
        }

        public Criteria andXmmcEqualTo(String value) {
            addCriterion("xmmc =", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcNotEqualTo(String value) {
            addCriterion("xmmc <>", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcGreaterThan(String value) {
            addCriterion("xmmc >", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcGreaterThanOrEqualTo(String value) {
            addCriterion("xmmc >=", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcLessThan(String value) {
            addCriterion("xmmc <", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcLessThanOrEqualTo(String value) {
            addCriterion("xmmc <=", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcLike(String value) {
            addCriterion("xmmc like", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcNotLike(String value) {
            addCriterion("xmmc not like", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcIn(List<String> values) {
            addCriterion("xmmc in", values, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcNotIn(List<String> values) {
            addCriterion("xmmc not in", values, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcBetween(String value1, String value2) {
            addCriterion("xmmc between", value1, value2, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcNotBetween(String value1, String value2) {
            addCriterion("xmmc not between", value1, value2, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmsmIsNull() {
            addCriterion("xmsm is null");
            return (Criteria) this;
        }

        public Criteria andXmsmIsNotNull() {
            addCriterion("xmsm is not null");
            return (Criteria) this;
        }

        public Criteria andXmsmEqualTo(String value) {
            addCriterion("xmsm =", value, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmNotEqualTo(String value) {
            addCriterion("xmsm <>", value, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmGreaterThan(String value) {
            addCriterion("xmsm >", value, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmGreaterThanOrEqualTo(String value) {
            addCriterion("xmsm >=", value, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmLessThan(String value) {
            addCriterion("xmsm <", value, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmLessThanOrEqualTo(String value) {
            addCriterion("xmsm <=", value, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmLike(String value) {
            addCriterion("xmsm like", value, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmNotLike(String value) {
            addCriterion("xmsm not like", value, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmIn(List<String> values) {
            addCriterion("xmsm in", values, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmNotIn(List<String> values) {
            addCriterion("xmsm not in", values, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmBetween(String value1, String value2) {
            addCriterion("xmsm between", value1, value2, "xmsm");
            return (Criteria) this;
        }

        public Criteria andXmsmNotBetween(String value1, String value2) {
            addCriterion("xmsm not between", value1, value2, "xmsm");
            return (Criteria) this;
        }

        public Criteria andSsdIsNull() {
            addCriterion("ssd is null");
            return (Criteria) this;
        }

        public Criteria andSsdIsNotNull() {
            addCriterion("ssd is not null");
            return (Criteria) this;
        }

        public Criteria andSsdEqualTo(String value) {
            addCriterion("ssd =", value, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdNotEqualTo(String value) {
            addCriterion("ssd <>", value, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdGreaterThan(String value) {
            addCriterion("ssd >", value, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdGreaterThanOrEqualTo(String value) {
            addCriterion("ssd >=", value, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdLessThan(String value) {
            addCriterion("ssd <", value, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdLessThanOrEqualTo(String value) {
            addCriterion("ssd <=", value, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdLike(String value) {
            addCriterion("ssd like", value, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdNotLike(String value) {
            addCriterion("ssd not like", value, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdIn(List<String> values) {
            addCriterion("ssd in", values, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdNotIn(List<String> values) {
            addCriterion("ssd not in", values, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdBetween(String value1, String value2) {
            addCriterion("ssd between", value1, value2, "ssd");
            return (Criteria) this;
        }

        public Criteria andSsdNotBetween(String value1, String value2) {
            addCriterion("ssd not between", value1, value2, "ssd");
            return (Criteria) this;
        }

        public Criteria andFzrIsNull() {
            addCriterion("fzr is null");
            return (Criteria) this;
        }

        public Criteria andFzrIsNotNull() {
            addCriterion("fzr is not null");
            return (Criteria) this;
        }

        public Criteria andFzrEqualTo(Integer value) {
            addCriterion("fzr =", value, "fzr");
            return (Criteria) this;
        }

        public Criteria andFzrNotEqualTo(Integer value) {
            addCriterion("fzr <>", value, "fzr");
            return (Criteria) this;
        }

        public Criteria andFzrGreaterThan(Integer value) {
            addCriterion("fzr >", value, "fzr");
            return (Criteria) this;
        }

        public Criteria andFzrGreaterThanOrEqualTo(Integer value) {
            addCriterion("fzr >=", value, "fzr");
            return (Criteria) this;
        }

        public Criteria andFzrLessThan(Integer value) {
            addCriterion("fzr <", value, "fzr");
            return (Criteria) this;
        }

        public Criteria andFzrLessThanOrEqualTo(Integer value) {
            addCriterion("fzr <=", value, "fzr");
            return (Criteria) this;
        }

        public Criteria andFzrIn(List<Integer> values) {
            addCriterion("fzr in", values, "fzr");
            return (Criteria) this;
        }

        public Criteria andFzrNotIn(List<Integer> values) {
            addCriterion("fzr not in", values, "fzr");
            return (Criteria) this;
        }

        public Criteria andFzrBetween(Integer value1, Integer value2) {
            addCriterion("fzr between", value1, value2, "fzr");
            return (Criteria) this;
        }

        public Criteria andFzrNotBetween(Integer value1, Integer value2) {
            addCriterion("fzr not between", value1, value2, "fzr");
            return (Criteria) this;
        }

        public Criteria andCwkmglIsNull() {
            addCriterion("cwkmgl is null");
            return (Criteria) this;
        }

        public Criteria andCwkmglIsNotNull() {
            addCriterion("cwkmgl is not null");
            return (Criteria) this;
        }

        public Criteria andCwkmglEqualTo(String value) {
            addCriterion("cwkmgl =", value, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglNotEqualTo(String value) {
            addCriterion("cwkmgl <>", value, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglGreaterThan(String value) {
            addCriterion("cwkmgl >", value, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglGreaterThanOrEqualTo(String value) {
            addCriterion("cwkmgl >=", value, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglLessThan(String value) {
            addCriterion("cwkmgl <", value, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglLessThanOrEqualTo(String value) {
            addCriterion("cwkmgl <=", value, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglLike(String value) {
            addCriterion("cwkmgl like", value, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglNotLike(String value) {
            addCriterion("cwkmgl not like", value, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglIn(List<String> values) {
            addCriterion("cwkmgl in", values, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglNotIn(List<String> values) {
            addCriterion("cwkmgl not in", values, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglBetween(String value1, String value2) {
            addCriterion("cwkmgl between", value1, value2, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andCwkmglNotBetween(String value1, String value2) {
            addCriterion("cwkmgl not between", value1, value2, "cwkmgl");
            return (Criteria) this;
        }

        public Criteria andSflxIsNull() {
            addCriterion("sflx is null");
            return (Criteria) this;
        }

        public Criteria andSflxIsNotNull() {
            addCriterion("sflx is not null");
            return (Criteria) this;
        }

        public Criteria andSflxEqualTo(String value) {
            addCriterion("sflx =", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxNotEqualTo(String value) {
            addCriterion("sflx <>", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxGreaterThan(String value) {
            addCriterion("sflx >", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxGreaterThanOrEqualTo(String value) {
            addCriterion("sflx >=", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxLessThan(String value) {
            addCriterion("sflx <", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxLessThanOrEqualTo(String value) {
            addCriterion("sflx <=", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxLike(String value) {
            addCriterion("sflx like", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxNotLike(String value) {
            addCriterion("sflx not like", value, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxIn(List<String> values) {
            addCriterion("sflx in", values, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxNotIn(List<String> values) {
            addCriterion("sflx not in", values, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxBetween(String value1, String value2) {
            addCriterion("sflx between", value1, value2, "sflx");
            return (Criteria) this;
        }

        public Criteria andSflxNotBetween(String value1, String value2) {
            addCriterion("sflx not between", value1, value2, "sflx");
            return (Criteria) this;
        }

        public Criteria andXmflIsNull() {
            addCriterion("xmfl is null");
            return (Criteria) this;
        }

        public Criteria andXmflIsNotNull() {
            addCriterion("xmfl is not null");
            return (Criteria) this;
        }

        public Criteria andXmflEqualTo(Integer value) {
            addCriterion("xmfl =", value, "xmfl");
            return (Criteria) this;
        }

        public Criteria andXmflNotEqualTo(Integer value) {
            addCriterion("xmfl <>", value, "xmfl");
            return (Criteria) this;
        }

        public Criteria andXmflGreaterThan(Integer value) {
            addCriterion("xmfl >", value, "xmfl");
            return (Criteria) this;
        }

        public Criteria andXmflGreaterThanOrEqualTo(Integer value) {
            addCriterion("xmfl >=", value, "xmfl");
            return (Criteria) this;
        }

        public Criteria andXmflLessThan(Integer value) {
            addCriterion("xmfl <", value, "xmfl");
            return (Criteria) this;
        }

        public Criteria andXmflLessThanOrEqualTo(Integer value) {
            addCriterion("xmfl <=", value, "xmfl");
            return (Criteria) this;
        }

        public Criteria andXmflIn(List<Integer> values) {
            addCriterion("xmfl in", values, "xmfl");
            return (Criteria) this;
        }

        public Criteria andXmflNotIn(List<Integer> values) {
            addCriterion("xmfl not in", values, "xmfl");
            return (Criteria) this;
        }

        public Criteria andXmflBetween(Integer value1, Integer value2) {
            addCriterion("xmfl between", value1, value2, "xmfl");
            return (Criteria) this;
        }

        public Criteria andXmflNotBetween(Integer value1, Integer value2) {
            addCriterion("xmfl not between", value1, value2, "xmfl");
            return (Criteria) this;
        }

        public Criteria andFygsbmIsNull() {
            addCriterion("fygsbm is null");
            return (Criteria) this;
        }

        public Criteria andFygsbmIsNotNull() {
            addCriterion("fygsbm is not null");
            return (Criteria) this;
        }

        public Criteria andFygsbmEqualTo(Integer value) {
            addCriterion("fygsbm =", value, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andFygsbmNotEqualTo(Integer value) {
            addCriterion("fygsbm <>", value, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andFygsbmGreaterThan(Integer value) {
            addCriterion("fygsbm >", value, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andFygsbmGreaterThanOrEqualTo(Integer value) {
            addCriterion("fygsbm >=", value, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andFygsbmLessThan(Integer value) {
            addCriterion("fygsbm <", value, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andFygsbmLessThanOrEqualTo(Integer value) {
            addCriterion("fygsbm <=", value, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andFygsbmIn(List<Integer> values) {
            addCriterion("fygsbm in", values, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andFygsbmNotIn(List<Integer> values) {
            addCriterion("fygsbm not in", values, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andFygsbmBetween(Integer value1, Integer value2) {
            addCriterion("fygsbm between", value1, value2, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andFygsbmNotBetween(Integer value1, Integer value2) {
            addCriterion("fygsbm not between", value1, value2, "fygsbm");
            return (Criteria) this;
        }

        public Criteria andSxIsNull() {
            addCriterion("sx is null");
            return (Criteria) this;
        }

        public Criteria andSxIsNotNull() {
            addCriterion("sx is not null");
            return (Criteria) this;
        }

        public Criteria andSxEqualTo(String value) {
            addCriterion("sx =", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxNotEqualTo(String value) {
            addCriterion("sx <>", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxGreaterThan(String value) {
            addCriterion("sx >", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxGreaterThanOrEqualTo(String value) {
            addCriterion("sx >=", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxLessThan(String value) {
            addCriterion("sx <", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxLessThanOrEqualTo(String value) {
            addCriterion("sx <=", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxLike(String value) {
            addCriterion("sx like", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxNotLike(String value) {
            addCriterion("sx not like", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxIn(List<String> values) {
            addCriterion("sx in", values, "sx");
            return (Criteria) this;
        }

        public Criteria andSxNotIn(List<String> values) {
            addCriterion("sx not in", values, "sx");
            return (Criteria) this;
        }

        public Criteria andSxBetween(String value1, String value2) {
            addCriterion("sx between", value1, value2, "sx");
            return (Criteria) this;
        }

        public Criteria andSxNotBetween(String value1, String value2) {
            addCriterion("sx not between", value1, value2, "sx");
            return (Criteria) this;
        }

        public Criteria andQdxIsNull() {
            addCriterion("qdx is null");
            return (Criteria) this;
        }

        public Criteria andQdxIsNotNull() {
            addCriterion("qdx is not null");
            return (Criteria) this;
        }

        public Criteria andQdxEqualTo(String value) {
            addCriterion("qdx =", value, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxNotEqualTo(String value) {
            addCriterion("qdx <>", value, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxGreaterThan(String value) {
            addCriterion("qdx >", value, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxGreaterThanOrEqualTo(String value) {
            addCriterion("qdx >=", value, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxLessThan(String value) {
            addCriterion("qdx <", value, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxLessThanOrEqualTo(String value) {
            addCriterion("qdx <=", value, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxLike(String value) {
            addCriterion("qdx like", value, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxNotLike(String value) {
            addCriterion("qdx not like", value, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxIn(List<String> values) {
            addCriterion("qdx in", values, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxNotIn(List<String> values) {
            addCriterion("qdx not in", values, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxBetween(String value1, String value2) {
            addCriterion("qdx between", value1, value2, "qdx");
            return (Criteria) this;
        }

        public Criteria andQdxNotBetween(String value1, String value2) {
            addCriterion("qdx not between", value1, value2, "qdx");
            return (Criteria) this;
        }

        public Criteria andGysIsNull() {
            addCriterion("gys is null");
            return (Criteria) this;
        }

        public Criteria andGysIsNotNull() {
            addCriterion("gys is not null");
            return (Criteria) this;
        }

        public Criteria andGysEqualTo(Integer value) {
            addCriterion("gys =", value, "gys");
            return (Criteria) this;
        }

        public Criteria andGysNotEqualTo(Integer value) {
            addCriterion("gys <>", value, "gys");
            return (Criteria) this;
        }

        public Criteria andGysGreaterThan(Integer value) {
            addCriterion("gys >", value, "gys");
            return (Criteria) this;
        }

        public Criteria andGysGreaterThanOrEqualTo(Integer value) {
            addCriterion("gys >=", value, "gys");
            return (Criteria) this;
        }

        public Criteria andGysLessThan(Integer value) {
            addCriterion("gys <", value, "gys");
            return (Criteria) this;
        }

        public Criteria andGysLessThanOrEqualTo(Integer value) {
            addCriterion("gys <=", value, "gys");
            return (Criteria) this;
        }

        public Criteria andGysIn(List<Integer> values) {
            addCriterion("gys in", values, "gys");
            return (Criteria) this;
        }

        public Criteria andGysNotIn(List<Integer> values) {
            addCriterion("gys not in", values, "gys");
            return (Criteria) this;
        }

        public Criteria andGysBetween(Integer value1, Integer value2) {
            addCriterion("gys between", value1, value2, "gys");
            return (Criteria) this;
        }

        public Criteria andGysNotBetween(Integer value1, Integer value2) {
            addCriterion("gys not between", value1, value2, "gys");
            return (Criteria) this;
        }

        public Criteria andDyywIsNull() {
            addCriterion("dyyw is null");
            return (Criteria) this;
        }

        public Criteria andDyywIsNotNull() {
            addCriterion("dyyw is not null");
            return (Criteria) this;
        }

        public Criteria andDyywEqualTo(String value) {
            addCriterion("dyyw =", value, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywNotEqualTo(String value) {
            addCriterion("dyyw <>", value, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywGreaterThan(String value) {
            addCriterion("dyyw >", value, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywGreaterThanOrEqualTo(String value) {
            addCriterion("dyyw >=", value, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywLessThan(String value) {
            addCriterion("dyyw <", value, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywLessThanOrEqualTo(String value) {
            addCriterion("dyyw <=", value, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywLike(String value) {
            addCriterion("dyyw like", value, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywNotLike(String value) {
            addCriterion("dyyw not like", value, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywIn(List<String> values) {
            addCriterion("dyyw in", values, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywNotIn(List<String> values) {
            addCriterion("dyyw not in", values, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywBetween(String value1, String value2) {
            addCriterion("dyyw between", value1, value2, "dyyw");
            return (Criteria) this;
        }

        public Criteria andDyywNotBetween(String value1, String value2) {
            addCriterion("dyyw not between", value1, value2, "dyyw");
            return (Criteria) this;
        }

        public Criteria andByyxjIsNull() {
            addCriterion("byyxj is null");
            return (Criteria) this;
        }

        public Criteria andByyxjIsNotNull() {
            addCriterion("byyxj is not null");
            return (Criteria) this;
        }

        public Criteria andByyxjEqualTo(String value) {
            addCriterion("byyxj =", value, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjNotEqualTo(String value) {
            addCriterion("byyxj <>", value, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjGreaterThan(String value) {
            addCriterion("byyxj >", value, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjGreaterThanOrEqualTo(String value) {
            addCriterion("byyxj >=", value, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjLessThan(String value) {
            addCriterion("byyxj <", value, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjLessThanOrEqualTo(String value) {
            addCriterion("byyxj <=", value, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjLike(String value) {
            addCriterion("byyxj like", value, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjNotLike(String value) {
            addCriterion("byyxj not like", value, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjIn(List<String> values) {
            addCriterion("byyxj in", values, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjNotIn(List<String> values) {
            addCriterion("byyxj not in", values, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjBetween(String value1, String value2) {
            addCriterion("byyxj between", value1, value2, "byyxj");
            return (Criteria) this;
        }

        public Criteria andByyxjNotBetween(String value1, String value2) {
            addCriterion("byyxj not between", value1, value2, "byyxj");
            return (Criteria) this;
        }

        public Criteria andDyywbkIsNull() {
            addCriterion("dyywbk is null");
            return (Criteria) this;
        }

        public Criteria andDyywbkIsNotNull() {
            addCriterion("dyywbk is not null");
            return (Criteria) this;
        }

        public Criteria andDyywbkEqualTo(String value) {
            addCriterion("dyywbk =", value, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkNotEqualTo(String value) {
            addCriterion("dyywbk <>", value, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkGreaterThan(String value) {
            addCriterion("dyywbk >", value, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkGreaterThanOrEqualTo(String value) {
            addCriterion("dyywbk >=", value, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkLessThan(String value) {
            addCriterion("dyywbk <", value, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkLessThanOrEqualTo(String value) {
            addCriterion("dyywbk <=", value, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkLike(String value) {
            addCriterion("dyywbk like", value, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkNotLike(String value) {
            addCriterion("dyywbk not like", value, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkIn(List<String> values) {
            addCriterion("dyywbk in", values, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkNotIn(List<String> values) {
            addCriterion("dyywbk not in", values, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkBetween(String value1, String value2) {
            addCriterion("dyywbk between", value1, value2, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andDyywbkNotBetween(String value1, String value2) {
            addCriterion("dyywbk not between", value1, value2, "dyywbk");
            return (Criteria) this;
        }

        public Criteria andZcfsIsNull() {
            addCriterion("zcfs is null");
            return (Criteria) this;
        }

        public Criteria andZcfsIsNotNull() {
            addCriterion("zcfs is not null");
            return (Criteria) this;
        }

        public Criteria andZcfsEqualTo(String value) {
            addCriterion("zcfs =", value, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsNotEqualTo(String value) {
            addCriterion("zcfs <>", value, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsGreaterThan(String value) {
            addCriterion("zcfs >", value, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsGreaterThanOrEqualTo(String value) {
            addCriterion("zcfs >=", value, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsLessThan(String value) {
            addCriterion("zcfs <", value, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsLessThanOrEqualTo(String value) {
            addCriterion("zcfs <=", value, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsLike(String value) {
            addCriterion("zcfs like", value, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsNotLike(String value) {
            addCriterion("zcfs not like", value, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsIn(List<String> values) {
            addCriterion("zcfs in", values, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsNotIn(List<String> values) {
            addCriterion("zcfs not in", values, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsBetween(String value1, String value2) {
            addCriterion("zcfs between", value1, value2, "zcfs");
            return (Criteria) this;
        }

        public Criteria andZcfsNotBetween(String value1, String value2) {
            addCriterion("zcfs not between", value1, value2, "zcfs");
            return (Criteria) this;
        }

        public Criteria andItjsfyIsNull() {
            addCriterion("itjsfy is null");
            return (Criteria) this;
        }

        public Criteria andItjsfyIsNotNull() {
            addCriterion("itjsfy is not null");
            return (Criteria) this;
        }

        public Criteria andItjsfyEqualTo(String value) {
            addCriterion("itjsfy =", value, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyNotEqualTo(String value) {
            addCriterion("itjsfy <>", value, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyGreaterThan(String value) {
            addCriterion("itjsfy >", value, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyGreaterThanOrEqualTo(String value) {
            addCriterion("itjsfy >=", value, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyLessThan(String value) {
            addCriterion("itjsfy <", value, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyLessThanOrEqualTo(String value) {
            addCriterion("itjsfy <=", value, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyLike(String value) {
            addCriterion("itjsfy like", value, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyNotLike(String value) {
            addCriterion("itjsfy not like", value, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyIn(List<String> values) {
            addCriterion("itjsfy in", values, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyNotIn(List<String> values) {
            addCriterion("itjsfy not in", values, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyBetween(String value1, String value2) {
            addCriterion("itjsfy between", value1, value2, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItjsfyNotBetween(String value1, String value2) {
            addCriterion("itjsfy not between", value1, value2, "itjsfy");
            return (Criteria) this;
        }

        public Criteria andItywcbIsNull() {
            addCriterion("itywcb is null");
            return (Criteria) this;
        }

        public Criteria andItywcbIsNotNull() {
            addCriterion("itywcb is not null");
            return (Criteria) this;
        }

        public Criteria andItywcbEqualTo(String value) {
            addCriterion("itywcb =", value, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbNotEqualTo(String value) {
            addCriterion("itywcb <>", value, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbGreaterThan(String value) {
            addCriterion("itywcb >", value, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbGreaterThanOrEqualTo(String value) {
            addCriterion("itywcb >=", value, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbLessThan(String value) {
            addCriterion("itywcb <", value, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbLessThanOrEqualTo(String value) {
            addCriterion("itywcb <=", value, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbLike(String value) {
            addCriterion("itywcb like", value, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbNotLike(String value) {
            addCriterion("itywcb not like", value, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbIn(List<String> values) {
            addCriterion("itywcb in", values, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbNotIn(List<String> values) {
            addCriterion("itywcb not in", values, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbBetween(String value1, String value2) {
            addCriterion("itywcb between", value1, value2, "itywcb");
            return (Criteria) this;
        }

        public Criteria andItywcbNotBetween(String value1, String value2) {
            addCriterion("itywcb not between", value1, value2, "itywcb");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysIsNull() {
            addCriterion("wnysyzjnys is null");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysIsNotNull() {
            addCriterion("wnysyzjnys is not null");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysEqualTo(String value) {
            addCriterion("wnysyzjnys =", value, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysNotEqualTo(String value) {
            addCriterion("wnysyzjnys <>", value, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysGreaterThan(String value) {
            addCriterion("wnysyzjnys >", value, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysGreaterThanOrEqualTo(String value) {
            addCriterion("wnysyzjnys >=", value, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysLessThan(String value) {
            addCriterion("wnysyzjnys <", value, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysLessThanOrEqualTo(String value) {
            addCriterion("wnysyzjnys <=", value, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysLike(String value) {
            addCriterion("wnysyzjnys like", value, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysNotLike(String value) {
            addCriterion("wnysyzjnys not like", value, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysIn(List<String> values) {
            addCriterion("wnysyzjnys in", values, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysNotIn(List<String> values) {
            addCriterion("wnysyzjnys not in", values, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysBetween(String value1, String value2) {
            addCriterion("wnysyzjnys between", value1, value2, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andWnysyzjnysNotBetween(String value1, String value2) {
            addCriterion("wnysyzjnys not between", value1, value2, "wnysyzjnys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysIsNull() {
            addCriterion("cxywkzys is null");
            return (Criteria) this;
        }

        public Criteria andCxywkzysIsNotNull() {
            addCriterion("cxywkzys is not null");
            return (Criteria) this;
        }

        public Criteria andCxywkzysEqualTo(String value) {
            addCriterion("cxywkzys =", value, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysNotEqualTo(String value) {
            addCriterion("cxywkzys <>", value, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysGreaterThan(String value) {
            addCriterion("cxywkzys >", value, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysGreaterThanOrEqualTo(String value) {
            addCriterion("cxywkzys >=", value, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysLessThan(String value) {
            addCriterion("cxywkzys <", value, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysLessThanOrEqualTo(String value) {
            addCriterion("cxywkzys <=", value, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysLike(String value) {
            addCriterion("cxywkzys like", value, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysNotLike(String value) {
            addCriterion("cxywkzys not like", value, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysIn(List<String> values) {
            addCriterion("cxywkzys in", values, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysNotIn(List<String> values) {
            addCriterion("cxywkzys not in", values, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysBetween(String value1, String value2) {
            addCriterion("cxywkzys between", value1, value2, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andCxywkzysNotBetween(String value1, String value2) {
            addCriterion("cxywkzys not between", value1, value2, "cxywkzys");
            return (Criteria) this;
        }

        public Criteria andGdgxzcIsNull() {
            addCriterion("gdgxzc is null");
            return (Criteria) this;
        }

        public Criteria andGdgxzcIsNotNull() {
            addCriterion("gdgxzc is not null");
            return (Criteria) this;
        }

        public Criteria andGdgxzcEqualTo(String value) {
            addCriterion("gdgxzc =", value, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcNotEqualTo(String value) {
            addCriterion("gdgxzc <>", value, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcGreaterThan(String value) {
            addCriterion("gdgxzc >", value, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcGreaterThanOrEqualTo(String value) {
            addCriterion("gdgxzc >=", value, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcLessThan(String value) {
            addCriterion("gdgxzc <", value, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcLessThanOrEqualTo(String value) {
            addCriterion("gdgxzc <=", value, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcLike(String value) {
            addCriterion("gdgxzc like", value, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcNotLike(String value) {
            addCriterion("gdgxzc not like", value, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcIn(List<String> values) {
            addCriterion("gdgxzc in", values, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcNotIn(List<String> values) {
            addCriterion("gdgxzc not in", values, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcBetween(String value1, String value2) {
            addCriterion("gdgxzc between", value1, value2, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andGdgxzcNotBetween(String value1, String value2) {
            addCriterion("gdgxzc not between", value1, value2, "gdgxzc");
            return (Criteria) this;
        }

        public Criteria andZlywzzIsNull() {
            addCriterion("zlywzz is null");
            return (Criteria) this;
        }

        public Criteria andZlywzzIsNotNull() {
            addCriterion("zlywzz is not null");
            return (Criteria) this;
        }

        public Criteria andZlywzzEqualTo(String value) {
            addCriterion("zlywzz =", value, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzNotEqualTo(String value) {
            addCriterion("zlywzz <>", value, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzGreaterThan(String value) {
            addCriterion("zlywzz >", value, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzGreaterThanOrEqualTo(String value) {
            addCriterion("zlywzz >=", value, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzLessThan(String value) {
            addCriterion("zlywzz <", value, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzLessThanOrEqualTo(String value) {
            addCriterion("zlywzz <=", value, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzLike(String value) {
            addCriterion("zlywzz like", value, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzNotLike(String value) {
            addCriterion("zlywzz not like", value, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzIn(List<String> values) {
            addCriterion("zlywzz in", values, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzNotIn(List<String> values) {
            addCriterion("zlywzz not in", values, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzBetween(String value1, String value2) {
            addCriterion("zlywzz between", value1, value2, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andZlywzzNotBetween(String value1, String value2) {
            addCriterion("zlywzz not between", value1, value2, "zlywzz");
            return (Criteria) this;
        }

        public Criteria andTsxlIsNull() {
            addCriterion("tsxl is null");
            return (Criteria) this;
        }

        public Criteria andTsxlIsNotNull() {
            addCriterion("tsxl is not null");
            return (Criteria) this;
        }

        public Criteria andTsxlEqualTo(String value) {
            addCriterion("tsxl =", value, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlNotEqualTo(String value) {
            addCriterion("tsxl <>", value, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlGreaterThan(String value) {
            addCriterion("tsxl >", value, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlGreaterThanOrEqualTo(String value) {
            addCriterion("tsxl >=", value, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlLessThan(String value) {
            addCriterion("tsxl <", value, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlLessThanOrEqualTo(String value) {
            addCriterion("tsxl <=", value, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlLike(String value) {
            addCriterion("tsxl like", value, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlNotLike(String value) {
            addCriterion("tsxl not like", value, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlIn(List<String> values) {
            addCriterion("tsxl in", values, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlNotIn(List<String> values) {
            addCriterion("tsxl not in", values, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlBetween(String value1, String value2) {
            addCriterion("tsxl between", value1, value2, "tsxl");
            return (Criteria) this;
        }

        public Criteria andTsxlNotBetween(String value1, String value2) {
            addCriterion("tsxl not between", value1, value2, "tsxl");
            return (Criteria) this;
        }

        public Criteria andXmsxIsNull() {
            addCriterion("xmsx is null");
            return (Criteria) this;
        }

        public Criteria andXmsxIsNotNull() {
            addCriterion("xmsx is not null");
            return (Criteria) this;
        }

        public Criteria andXmsxEqualTo(String value) {
            addCriterion("xmsx =", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxNotEqualTo(String value) {
            addCriterion("xmsx <>", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxGreaterThan(String value) {
            addCriterion("xmsx >", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxGreaterThanOrEqualTo(String value) {
            addCriterion("xmsx >=", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxLessThan(String value) {
            addCriterion("xmsx <", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxLessThanOrEqualTo(String value) {
            addCriterion("xmsx <=", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxLike(String value) {
            addCriterion("xmsx like", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxNotLike(String value) {
            addCriterion("xmsx not like", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxIn(List<String> values) {
            addCriterion("xmsx in", values, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxNotIn(List<String> values) {
            addCriterion("xmsx not in", values, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxBetween(String value1, String value2) {
            addCriterion("xmsx between", value1, value2, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxNotBetween(String value1, String value2) {
            addCriterion("xmsx not between", value1, value2, "xmsx");
            return (Criteria) this;
        }

        public Criteria andCxkyIsNull() {
            addCriterion("cxky is null");
            return (Criteria) this;
        }

        public Criteria andCxkyIsNotNull() {
            addCriterion("cxky is not null");
            return (Criteria) this;
        }

        public Criteria andCxkyEqualTo(String value) {
            addCriterion("cxky =", value, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyNotEqualTo(String value) {
            addCriterion("cxky <>", value, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyGreaterThan(String value) {
            addCriterion("cxky >", value, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyGreaterThanOrEqualTo(String value) {
            addCriterion("cxky >=", value, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyLessThan(String value) {
            addCriterion("cxky <", value, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyLessThanOrEqualTo(String value) {
            addCriterion("cxky <=", value, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyLike(String value) {
            addCriterion("cxky like", value, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyNotLike(String value) {
            addCriterion("cxky not like", value, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyIn(List<String> values) {
            addCriterion("cxky in", values, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyNotIn(List<String> values) {
            addCriterion("cxky not in", values, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyBetween(String value1, String value2) {
            addCriterion("cxky between", value1, value2, "cxky");
            return (Criteria) this;
        }

        public Criteria andCxkyNotBetween(String value1, String value2) {
            addCriterion("cxky not between", value1, value2, "cxky");
            return (Criteria) this;
        }

        public Criteria andQtxmIsNull() {
            addCriterion("qtxm is null");
            return (Criteria) this;
        }

        public Criteria andQtxmIsNotNull() {
            addCriterion("qtxm is not null");
            return (Criteria) this;
        }

        public Criteria andQtxmEqualTo(String value) {
            addCriterion("qtxm =", value, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmNotEqualTo(String value) {
            addCriterion("qtxm <>", value, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmGreaterThan(String value) {
            addCriterion("qtxm >", value, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmGreaterThanOrEqualTo(String value) {
            addCriterion("qtxm >=", value, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmLessThan(String value) {
            addCriterion("qtxm <", value, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmLessThanOrEqualTo(String value) {
            addCriterion("qtxm <=", value, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmLike(String value) {
            addCriterion("qtxm like", value, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmNotLike(String value) {
            addCriterion("qtxm not like", value, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmIn(List<String> values) {
            addCriterion("qtxm in", values, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmNotIn(List<String> values) {
            addCriterion("qtxm not in", values, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmBetween(String value1, String value2) {
            addCriterion("qtxm between", value1, value2, "qtxm");
            return (Criteria) this;
        }

        public Criteria andQtxmNotBetween(String value1, String value2) {
            addCriterion("qtxm not between", value1, value2, "qtxm");
            return (Criteria) this;
        }

        public Criteria andZysIsNull() {
            addCriterion("zys is null");
            return (Criteria) this;
        }

        public Criteria andZysIsNotNull() {
            addCriterion("zys is not null");
            return (Criteria) this;
        }

        public Criteria andZysEqualTo(String value) {
            addCriterion("zys =", value, "zys");
            return (Criteria) this;
        }

        public Criteria andZysNotEqualTo(String value) {
            addCriterion("zys <>", value, "zys");
            return (Criteria) this;
        }

        public Criteria andZysGreaterThan(String value) {
            addCriterion("zys >", value, "zys");
            return (Criteria) this;
        }

        public Criteria andZysGreaterThanOrEqualTo(String value) {
            addCriterion("zys >=", value, "zys");
            return (Criteria) this;
        }

        public Criteria andZysLessThan(String value) {
            addCriterion("zys <", value, "zys");
            return (Criteria) this;
        }

        public Criteria andZysLessThanOrEqualTo(String value) {
            addCriterion("zys <=", value, "zys");
            return (Criteria) this;
        }

        public Criteria andZysLike(String value) {
            addCriterion("zys like", value, "zys");
            return (Criteria) this;
        }

        public Criteria andZysNotLike(String value) {
            addCriterion("zys not like", value, "zys");
            return (Criteria) this;
        }

        public Criteria andZysIn(List<String> values) {
            addCriterion("zys in", values, "zys");
            return (Criteria) this;
        }

        public Criteria andZysNotIn(List<String> values) {
            addCriterion("zys not in", values, "zys");
            return (Criteria) this;
        }

        public Criteria andZysBetween(String value1, String value2) {
            addCriterion("zys between", value1, value2, "zys");
            return (Criteria) this;
        }

        public Criteria andZysNotBetween(String value1, String value2) {
            addCriterion("zys not between", value1, value2, "zys");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("bz is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("bz is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("bz =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("bz <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("bz >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("bz >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("bz <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("bz <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("bz like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("bz not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("bz in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("bz not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("bz between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("bz not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNull() {
            addCriterion("reserved1 is null");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNotNull() {
            addCriterion("reserved1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved1EqualTo(String value) {
            addCriterion("reserved1 =", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotEqualTo(String value) {
            addCriterion("reserved1 <>", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThan(String value) {
            addCriterion("reserved1 >", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("reserved1 >=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThan(String value) {
            addCriterion("reserved1 <", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThanOrEqualTo(String value) {
            addCriterion("reserved1 <=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Like(String value) {
            addCriterion("reserved1 like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotLike(String value) {
            addCriterion("reserved1 not like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1In(List<String> values) {
            addCriterion("reserved1 in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotIn(List<String> values) {
            addCriterion("reserved1 not in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Between(String value1, String value2) {
            addCriterion("reserved1 between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotBetween(String value1, String value2) {
            addCriterion("reserved1 not between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNull() {
            addCriterion("reserved2 is null");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNotNull() {
            addCriterion("reserved2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved2EqualTo(String value) {
            addCriterion("reserved2 =", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotEqualTo(String value) {
            addCriterion("reserved2 <>", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThan(String value) {
            addCriterion("reserved2 >", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("reserved2 >=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThan(String value) {
            addCriterion("reserved2 <", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThanOrEqualTo(String value) {
            addCriterion("reserved2 <=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Like(String value) {
            addCriterion("reserved2 like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotLike(String value) {
            addCriterion("reserved2 not like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2In(List<String> values) {
            addCriterion("reserved2 in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotIn(List<String> values) {
            addCriterion("reserved2 not in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Between(String value1, String value2) {
            addCriterion("reserved2 between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotBetween(String value1, String value2) {
            addCriterion("reserved2 not between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved3IsNull() {
            addCriterion("reserved3 is null");
            return (Criteria) this;
        }

        public Criteria andReserved3IsNotNull() {
            addCriterion("reserved3 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved3EqualTo(String value) {
            addCriterion("reserved3 =", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotEqualTo(String value) {
            addCriterion("reserved3 <>", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3GreaterThan(String value) {
            addCriterion("reserved3 >", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3GreaterThanOrEqualTo(String value) {
            addCriterion("reserved3 >=", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3LessThan(String value) {
            addCriterion("reserved3 <", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3LessThanOrEqualTo(String value) {
            addCriterion("reserved3 <=", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3Like(String value) {
            addCriterion("reserved3 like", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotLike(String value) {
            addCriterion("reserved3 not like", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3In(List<String> values) {
            addCriterion("reserved3 in", values, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotIn(List<String> values) {
            addCriterion("reserved3 not in", values, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3Between(String value1, String value2) {
            addCriterion("reserved3 between", value1, value2, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotBetween(String value1, String value2) {
            addCriterion("reserved3 not between", value1, value2, "reserved3");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：bss_project_info
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 项目明细表
     * Criterion
     * 数据库表：bss_project_info
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}