package com.example.bss.pojo;

import java.io.Serializable;
import java.util.List;

public class BssProjectClass implements Serializable {
    /**
     * 主键id
     * 表字段 : bss_project_class.id
     */
    private Integer id;

    /**
     * 类别
     * 表字段 : bss_project_class.lb
     */
    private String lb;

    /**
     * 备注
     * 表字段 : bss_project_class.bz
     */
    private String bz;

    /**
     * 预留字段1
     * 表字段 : bss_project_class.reserved1
     */
    private String reserved1;

    /**
     * 预留字段2
     * 表字段 : bss_project_class.reserved2
     */
    private String reserved2;

    /**
     * 预留字段3
     * 表字段 : bss_project_class.reserved3
     */
    private String reserved3;

    /**
     * 创建时间
     * 表字段 : bss_project_class.create_time
     */
    private String createTime;

    /**
     * 修改时间
     * 表字段 : bss_project_class.update_time
     */
    private String updateTime;

    private List<BssProjectInfo> bssProjectInfos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_project_class
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键id 字段:bss_project_class.id
     *
     * @return bss_project_class.id, 主键id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键id 字段:bss_project_class.id
     *
     * @param id the value for bss_project_class.id, 主键id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 类别 字段:bss_project_class.lb
     *
     * @return bss_project_class.lb, 类别
     */
    public String getLb() {
        return lb;
    }

    /**
     * 设置 类别 字段:bss_project_class.lb
     *
     * @param lb the value for bss_project_class.lb, 类别
     */
    public void setLb(String lb) {
        this.lb = lb == null ? null : lb.trim();
    }

    /**
     * 获取 备注 字段:bss_project_class.bz
     *
     * @return bss_project_class.bz, 备注
     */
    public String getBz() {
        return bz;
    }

    /**
     * 设置 备注 字段:bss_project_class.bz
     *
     * @param bz the value for bss_project_class.bz, 备注
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * 获取 预留字段1 字段:bss_project_class.reserved1
     *
     * @return bss_project_class.reserved1, 预留字段1
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * 设置 预留字段1 字段:bss_project_class.reserved1
     *
     * @param reserved1 the value for bss_project_class.reserved1, 预留字段1
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * 获取 预留字段2 字段:bss_project_class.reserved2
     *
     * @return bss_project_class.reserved2, 预留字段2
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * 设置 预留字段2 字段:bss_project_class.reserved2
     *
     * @param reserved2 the value for bss_project_class.reserved2, 预留字段2
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * 获取 预留字段3 字段:bss_project_class.reserved3
     *
     * @return bss_project_class.reserved3, 预留字段3
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * 设置 预留字段3 字段:bss_project_class.reserved3
     *
     * @param reserved3 the value for bss_project_class.reserved3, 预留字段3
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * 获取 创建时间 字段:bss_project_class.create_time
     *
     * @return bss_project_class.create_time, 创建时间
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:bss_project_class.create_time
     *
     * @param createTime the value for bss_project_class.create_time, 创建时间
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * 获取 修改时间 字段:bss_project_class.update_time
     *
     * @return bss_project_class.update_time, 修改时间
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 修改时间 字段:bss_project_class.update_time
     *
     * @param updateTime the value for bss_project_class.update_time, 修改时间
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public List<BssProjectInfo> getBssProjectInfos() {
        return bssProjectInfos;
    }

    public void setBssProjectInfos(List<BssProjectInfo> bssProjectInfos) {
        this.bssProjectInfos=bssProjectInfos;
    }
}