package com.example.bss.pojo;

import java.io.Serializable;
import java.util.List;

public class BssProjectPerson implements Serializable {
    /**
     * 主键id
     * 表字段 : bss_project_person.id
     */
    private Integer id;

    /**
     * 姓名
     * 表字段 : bss_project_person.xm
     */
    private String xm;

    /**
     * 用户名
     * 表字段 : bss_project_person.username
     */
    private String username;

    /**
     * 密码
     * 表字段 : bss_project_person.password
     */
    private String password;

    /**
     * 备注
     * 表字段 : bss_project_person.bz
     */
    private String bz;

    /**
     * 电话
     * 表字段 : bss_project_person.phone
     */
    private String phone;

    /**
     * 邮箱
     * 表字段 : bss_project_person.email
     */
    private String email;

    /**
     * 部门
     * 表字段 : bss_project_person.department
     */
    private String department;

    /**
     * 创建时间
     * 表字段 : bss_project_person.create_time
     */
    private String createTime;

    /**
     * 修改时间
     * 表字段 : bss_project_person.update_time
     */
    private String updateTime;

    /**
     * 预留字段1
     * 表字段 : bss_project_person.reserved1
     */
    private String reserved1;

    private List<BssProjectInfo> bssProjectInfos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_project_person
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键id 字段:bss_project_person.id
     *
     * @return bss_project_person.id, 主键id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键id 字段:bss_project_person.id
     *
     * @param id the value for bss_project_person.id, 主键id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 姓名 字段:bss_project_person.xm
     *
     * @return bss_project_person.xm, 姓名
     */
    public String getXm() {
        return xm;
    }

    /**
     * 设置 姓名 字段:bss_project_person.xm
     *
     * @param xm the value for bss_project_person.xm, 姓名
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * 获取 用户名 字段:bss_project_person.username
     *
     * @return bss_project_person.username, 用户名
     */
    public String getUsername() {
        return username;
    }

    /**
     * 设置 用户名 字段:bss_project_person.username
     *
     * @param username the value for bss_project_person.username, 用户名
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * 获取 密码 字段:bss_project_person.password
     *
     * @return bss_project_person.password, 密码
     */
    public String getPassword() {
        return password;
    }

    /**
     * 设置 密码 字段:bss_project_person.password
     *
     * @param password the value for bss_project_person.password, 密码
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * 获取 备注 字段:bss_project_person.bz
     *
     * @return bss_project_person.bz, 备注
     */
    public String getBz() {
        return bz;
    }

    /**
     * 设置 备注 字段:bss_project_person.bz
     *
     * @param bz the value for bss_project_person.bz, 备注
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * 获取 电话 字段:bss_project_person.phone
     *
     * @return bss_project_person.phone, 电话
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置 电话 字段:bss_project_person.phone
     *
     * @param phone the value for bss_project_person.phone, 电话
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取 邮箱 字段:bss_project_person.email
     *
     * @return bss_project_person.email, 邮箱
     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置 邮箱 字段:bss_project_person.email
     *
     * @param email the value for bss_project_person.email, 邮箱
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 获取 部门 字段:bss_project_person.department
     *
     * @return bss_project_person.department, 部门
     */
    public String getDepartment() {
        return department;
    }

    /**
     * 设置 部门 字段:bss_project_person.department
     *
     * @param department the value for bss_project_person.department, 部门
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * 获取 创建时间 字段:bss_project_person.create_time
     *
     * @return bss_project_person.create_time, 创建时间
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:bss_project_person.create_time
     *
     * @param createTime the value for bss_project_person.create_time, 创建时间
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * 获取 修改时间 字段:bss_project_person.update_time
     *
     * @return bss_project_person.update_time, 修改时间
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 修改时间 字段:bss_project_person.update_time
     *
     * @param updateTime the value for bss_project_person.update_time, 修改时间
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * 获取 预留字段1 字段:bss_project_person.reserved1
     *
     * @return bss_project_person.reserved1, 预留字段1
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * 设置 预留字段1 字段:bss_project_person.reserved1
     *
     * @param reserved1 the value for bss_project_person.reserved1, 预留字段1
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    public List<BssProjectInfo> getBssProjectInfos() {
        return bssProjectInfos;
    }

    public void setBssProjectInfos(List<BssProjectInfo> bssProjectInfos) {
        this.bssProjectInfos=bssProjectInfos;
    }
}