package com.example.bss.pojo;

import java.io.Serializable;
import java.util.List;

public class BssSupplier implements Serializable {
    /**
     * 主键id
     * 表字段 : bss_supplier.id
     */
    private Integer id;

    /**
     * 供应商名称
     * 表字段 : bss_supplier.gysmc
     */
    private String gysmc;

    /**
     * 
     * 表字段 : bss_supplier.bz
     */
    private String bz;

    /**
     * 预留字段
     * 表字段 : bss_supplier.reserved1
     */
    private String reserved1;

    /**
     * 预留字段2
     * 表字段 : bss_supplier.reserved2
     */
    private String reserved2;

    /**
     * 预留 字段3
     * 表字段 : bss_supplier.reserved3
     */
    private String reserved3;

    /**
     * 创建时间
     * 表字段 : bss_supplier.create_time
     */
    private String createTime;

    /**
     * 修改时间
     * 表字段 : bss_supplier.update_time
     */
    private String updateTime;

    private List<BssProjectInfo> bssProjectInfos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_supplier
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键id 字段:bss_supplier.id
     *
     * @return bss_supplier.id, 主键id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键id 字段:bss_supplier.id
     *
     * @param id the value for bss_supplier.id, 主键id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 供应商名称 字段:bss_supplier.gysmc
     *
     * @return bss_supplier.gysmc, 供应商名称
     */
    public String getGysmc() {
        return gysmc;
    }

    /**
     * 设置 供应商名称 字段:bss_supplier.gysmc
     *
     * @param gysmc the value for bss_supplier.gysmc, 供应商名称
     */
    public void setGysmc(String gysmc) {
        this.gysmc = gysmc == null ? null : gysmc.trim();
    }

    /**
     * 获取  字段:bss_supplier.bz
     *
     * @return bss_supplier.bz, 
     */
    public String getBz() {
        return bz;
    }

    /**
     * 设置  字段:bss_supplier.bz
     *
     * @param bz the value for bss_supplier.bz, 
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * 获取 预留字段 字段:bss_supplier.reserved1
     *
     * @return bss_supplier.reserved1, 预留字段
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * 设置 预留字段 字段:bss_supplier.reserved1
     *
     * @param reserved1 the value for bss_supplier.reserved1, 预留字段
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * 获取 预留字段2 字段:bss_supplier.reserved2
     *
     * @return bss_supplier.reserved2, 预留字段2
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * 设置 预留字段2 字段:bss_supplier.reserved2
     *
     * @param reserved2 the value for bss_supplier.reserved2, 预留字段2
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * 获取 预留 字段3 字段:bss_supplier.reserved3
     *
     * @return bss_supplier.reserved3, 预留 字段3
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * 设置 预留 字段3 字段:bss_supplier.reserved3
     *
     * @param reserved3 the value for bss_supplier.reserved3, 预留 字段3
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * 获取 创建时间 字段:bss_supplier.create_time
     *
     * @return bss_supplier.create_time, 创建时间
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:bss_supplier.create_time
     *
     * @param createTime the value for bss_supplier.create_time, 创建时间
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * 获取 修改时间 字段:bss_supplier.update_time
     *
     * @return bss_supplier.update_time, 修改时间
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 修改时间 字段:bss_supplier.update_time
     *
     * @param updateTime the value for bss_supplier.update_time, 修改时间
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public List<BssProjectInfo> getBssProjectInfos() {
        return bssProjectInfos;
    }

    public void setBssProjectInfos(List<BssProjectInfo> bssProjectInfos) {
        this.bssProjectInfos=bssProjectInfos;
    }
}