package com.example.bss.pojo;

import java.io.Serializable;

public class BssSystemLog implements Serializable {
    /**
     * 主键
     * 表字段 : bss_system_log.id
     */
    private Integer id;

    /**
     * 类型
     * 表字段 : bss_system_log.lx
     */
    private String lx;

    /**
     * 内容
     * 表字段 : bss_system_log.nr
     */
    private String nr;

    /**
     * 用户名
     * 表字段 : bss_system_log.username
     */
    private String username;

    /**
     * 
     * 表字段 : bss_system_log.ip
     */
    private String ip;

    /**
     * 操作时间
     * 表字段 : bss_system_log.create_time
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bss_system_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:bss_system_log.id
     *
     * @return bss_system_log.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:bss_system_log.id
     *
     * @param id the value for bss_system_log.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 类型 字段:bss_system_log.lx
     *
     * @return bss_system_log.lx, 类型
     */
    public String getLx() {
        return lx;
    }

    /**
     * 设置 类型 字段:bss_system_log.lx
     *
     * @param lx the value for bss_system_log.lx, 类型
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * 获取 内容 字段:bss_system_log.nr
     *
     * @return bss_system_log.nr, 内容
     */
    public String getNr() {
        return nr;
    }

    /**
     * 设置 内容 字段:bss_system_log.nr
     *
     * @param nr the value for bss_system_log.nr, 内容
     */
    public void setNr(String nr) {
        this.nr = nr == null ? null : nr.trim();
    }

    /**
     * 获取 用户名 字段:bss_system_log.username
     *
     * @return bss_system_log.username, 用户名
     */
    public String getUsername() {
        return username;
    }

    /**
     * 设置 用户名 字段:bss_system_log.username
     *
     * @param username the value for bss_system_log.username, 用户名
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * 获取  字段:bss_system_log.ip
     *
     * @return bss_system_log.ip, 
     */
    public String getIp() {
        return ip;
    }

    /**
     * 设置  字段:bss_system_log.ip
     *
     * @param ip the value for bss_system_log.ip, 
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * 获取 操作时间 字段:bss_system_log.create_time
     *
     * @return bss_system_log.create_time, 操作时间
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 设置 操作时间 字段:bss_system_log.create_time
     *
     * @param createTime the value for bss_system_log.create_time, 操作时间
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}